name: Build and Release
on: push

jobs:
  weasyprint-build:
    name: Build WeasyPrint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer 
        run: make build/weasyprint-layer-python3.12.zip
      - name: Test weasyprint
        run: |
          mkdir output
          make test.start.container &
          sleep 1
          TEST_FILENAME=output/report.pdf make test.print.report
          rm -rf build/opt
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WeasyPrint Layer Build
          path: build
      - name: Upload Test PDF
        uses: actions/upload-artifact@v4
        with:
          name: WeasyPrint Test Results
          path: output
      - name: Create WeasyPrint Release
        if: startsWith(github.ref, 'refs/tags/weasyprint-')
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: |
            ./build/weasyprint-layer-python3.12.zip
            ./build/weasyprint-layer-python3.12-no-fonts.zip

  ghostscript-build:
    name: Build GhostScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer
        run: |
          make build/ghostscript-layer.zip
          rm -rf build/opt
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: GhostScript Layer Build
          path: build
      - name: Create GhostScript Release
        if: startsWith(github.ref, 'refs/tags/ghostscript-')
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: ./build/build/ghostscript-layer.zip
