name: Build and Release
on: push

jobs:
  weasyprint-build:
    name: Build WeasyPrint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') "
    steps:
      - uses: actions/checkout@v2
      - name: Build weasyprint
        run: |
          make build/weasyprint-layer-python3.12.zip
      - name: Test weasyprint
        run: |
          mkdir output
          make test.start.container &
          sleep 1
          TEST_FILENAME=output/report.pdf make test.print.report
      - name: Upload pdf
        uses: actions/upload-artifact@v1
        with:
          name: WeasyPrint test results
          path: output
      - name: Create WeasyPrint Release
        id: create_weasyprint_release
        if: startsWith(github.ref, 'refs/tags/weasyprint-')
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release WeasyPrint layer
      - name: Upload WeasyPrint Layer
        if: startsWith(github.ref, 'refs/tags/weasyprint-')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_weasyprint_release.outputs.upload_url }}
          asset_path: ./build/weasyprint-layer-python3.12.zip
          asset_name: weasyprint-layer-python3.12.zip
          asset_content_type: application/zip
